Update test.yml

diff --git a/.github/test.yml b/.github/test.yml
--- a/.github/test.yml
+++ b/.github/test.yml
@@ -14,15 +14,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Build
-      run: echo "Building..."
-    
-    - name: Set status
-      if: failure()
-      run: echo "::set-output name=status::failure"
-    - name: Set status
-      if: success()
-      run: echo "::set-output name=status::success"
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Build
+        run: echo "Building"
+      
+      - name: Save build status
+        id: save_build_status
+        if: always()
+        run: echo "var2=${{ job.status }}" >> $GITHUB_ENV
 
   test:
     name: Test
@@ -30,12 +31,55 @@ jobs:
     needs: build
 
     steps:
-    - name: Test
-      run: echo "Testing..."
-    
-    - name: Set status
-      if: failure()
-      run: echo "::set-output name=status::failure"
-    - name: Set status
-      if: success()
-      run: echo "::set-output name=status::success"
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Test
+        run: |
+          echo "Testing"
+          exit 1
+      
+      - name: Save test status
+        id: save_test_status
+        if: always()
+        run: echo "var1=${{ job.status }}" >> $GITHUB_ENV
+
+  overall_status:
+    name: Determine Overall Status
+    runs-on: ubuntu-latest
+    needs: [build, test]
+    if: always()
+    outputs:
+      overall-status: ${{ needs.overall_status.outputs.overall-status }}
+
+    steps:
+      - name: Set Overall Status
+        id: set_overall_status
+        run: |
+          build_status="${{ needs.build.outputs.var2 }}"
+          test_status="${{ needs.test.outputs.var1 }}"
+          # Check if both build and test were successful
+          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
+            echo "Overall Status: pass"
+            echo "::set-output name=overall-status::pass"
+            echo "Overall Status: pass" >> $GITHUB_ENV
+          else
+            echo "Overall Status: fail"
+            echo "::set-output name=overall-status::fail"
+            echo "Overall Status: fail" >> $GITHUB_ENV
+          fi
+
+  run_composite_action:
+    name: Run the Composite Action
+    if: always()
+    needs: [overall_status]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      
+      - name: Run the Composite Action
+        uses: ./.github/actions/build_and_notify
+        with:
+          action-name: ${{ github.workflow }}
+          overall-status: ${{ needs.overall_status.outputs.overall-status }}
