Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -41,7 +41,7 @@ jobs:
       - name: Test
         run: |
           echo "Testing..."
-          exit 1  # Simulating a failure for demonstration
+          # exit 1  # Simulating a failure for demonstration
 
       - name: Save test status
         id: save_test_status
@@ -66,9 +66,9 @@ jobs:
           echo "Test Status: $test_status"
           
           if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
-            overall_status="pass"
+            overall_status="PASS"
           else
-            overall_status="fail"
+            overall_status="FAIL"
           fi
 
           echo "Overall Status: $overall_status"
